name: CI

on: [push, pull_request]

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          clang-format --style=file --dry-run --Werror \
            $(git ls-files '*.cpp' '*.h' '*.hpp')

  tidy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy cmake g++ make ninja-build

      - name: Configure project
        run: cmake --preset ci

      - name: Run clang-tidy
        run: |
          clang-tidy -p build $(git ls-files '*.cpp' '*.h' '*.hpp') || exit 1

  build:
    needs: [fmt-check, tidy-check]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Bootstrap vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure (show CMake errors)
        run: cmake --preset ci

      - name: Build
        run: cmake --build --preset ci

      - name: Test (unit + smoke)
        run: BUILD_DIR=build ctest --preset ci --output-on-failure