name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Bootstrap vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure (show CMake errors)
        run: cmake --preset ci

      - name: Build
        run: cmake --build --preset ci

      - name: Test (unit + smoke)
        run: BUILD_DIR=build ctest --preset ci --output-on-failure